<a href="https://colab.research.google.com/github/sahikapathan/ML-FILE-71/blob/main/diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving diabetes.csv to diabetes.csv


In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv('diabetes.csv')

In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [ ]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [ ]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

### SVC Model Performance on Test Data

In [ ]:
from sklearn.metrics import classification_report, roc_auc_score

# Assuming y_test, y_pred_svm, and y_prob_svm are already defined from previous steps
print('Classification Report for SVC:')
print(classification_report(y_test, y_pred_svm))

roc_auc_svm = roc_auc_score(y_test, y_prob_svm[:,1])
print(f'ROC AUC Score for SVC: {roc_auc_svm}')

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [ ]:
df.size

6912

In [ ]:
df.shape

(768, 9)

In [ ]:
diabetes_counts = df['Outcome'].value_counts()
display(diabetes_counts)

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
#train and test split
from sklearn.model_selection import train_test_split
#train and test split is to avoid the data leakage

x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=42
)

# x_train -input data for training
# x_test -input data for testing
# y_train -correct answers for training
# y_test -correct answers for testing

# x_train + y_train - model learned
# x_test + y_test - model is evaluated
#stratify means spliting training and testing the data


NameError: name 'x' is not defined

In [ ]:
(df== 0).any()

Pregnancies                  True
Glucose                      True
BloodPressure                True
SkinThickness                True
Insulin                      True
BMI                          True
DiabetesPedigreeFunction    False
Age                         False
Outcome                      True
dtype: bool

In [ ]:
df.columns = df.columns.str.strip().str.lower()

In [ ]:
# columns where 0 is not a valid medical values
invalid_zero_cols = ['glucose', 'bloodpressure', 'skinthickness', 'insulin', 'bmi']

# replace zero with np.nan
df[invalid_zero_cols]=df[invalid_zero_cols].replace(0,np.nan)

In [ ]:
df.isnull().sum()

pregnancies                   0
glucose                       5
bloodpressure                35
skinthickness               227
insulin                     374
bmi                          11
diabetespedigreefunction      0
age                           0
outcome                       0
dtype: int64

In [ ]:
# input missing value
for col in invalid_zero_cols:
  df[col].fillna(df[col].median(),inplace=True)


# median represents: a typical patient not too high not too low
# not influenced by outliers

/tmp/ipython-input-644586416.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(),inplace=True)


In [ ]:
df.isnull().sum()

pregnancies                 0
glucose                     0
bloodpressure               0
skinthickness               0
insulin                     0
bmi                         0
diabetespedigreefunction    0
age                         0
outcome                     0
dtype: int64

In [ ]:
(df== 0).any()

pregnancies                  True
glucose                     False
bloodpressure               False
skinthickness               False
insulin                     False
bmi                         False
diabetespedigreefunction    False
age                         False
outcome                      True
dtype: bool

In [ ]:
# features target sepration
# feature
x=df.drop(columns=['outcome'])

# target
y=df['outcome']

# x contains all input features
# y contains target variable or what we want to predic
# use in prevent data leakage

In [ ]:
x.columns

Index(['pregnancies', 'glucose', 'bloodpressure', 'skinthickness', 'insulin',
       'bmi', 'diabetespedigreefunction', 'age'],
      dtype='object')

In [ ]:
y.name

'outcome'

In [ ]:
#train and test split
#train and test split
from sklearn.model_selection import train_test_split
#train and test split is to avoid the data leakage

x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=42,stratify=y

)

# x_train -input data for training
# x_test -input data for testing
# y_train -correct answers for training
# y_test -correct answers for testing

# x_train + y_train - model learned
# x_test + y_test - model is evaluated
#stratify means spliting training and testing the data(same/equal accuracy)


In [ ]:
x_train.shape

(614, 8)

In [ ]:
x_test.shape

(154, 8)

In [ ]:
x_train.dtypes

pregnancies                   int64
glucose                     float64
bloodpressure               float64
skinthickness               float64
insulin                     float64
bmi                         float64
diabetespedigreefunction    float64
age                           int64
dtype: object

In [ ]:
y.value_counts(normalize=True)

outcome
0    0.651042
1    0.348958
Name: proportion, dtype: float64

In [ ]:
y_train.value_counts(normalize=True)

outcome
0    0.651466
1    0.348534
Name: proportion, dtype: float64

In [ ]:
y_test.value_counts(normalize=True)

outcome
0    0.649351
1    0.350649
Name: proportion, dtype: float64

In [ ]:
# feature scalling-preprocessing

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [ ]:
# here using logistic regression classifier because it is binary classification
# problem ,strong baselines for medical data

from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()
log_reg.fit(x_train_scaled,y_train)

# here now the model trained, uses scalled features,can implimenet safely



LogisticRegression()

In [ ]:
y_pred = log_reg.predict(x_test_scaled)

In [ ]:
y_pred[:10]

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1])

In [ ]:
#Evaluated Model Performance:
log_reg.score(x_test_scaled,y_test)

0.7077922077922078

In [ ]:
log_reg.score(x_train_scaled,y_train)

0.7964169381107492

In [ ]:
# 1.Loaded the Dataset: We started by loading the diabetes.csv file into a pandas DataFrame.
# 2.Initial Data Inspection: We used df.head(), df.tail(), df.describe(), and df.info() to get a quick overview of the data
# 3.Checked for Missing Values: We initially checked for any null values using df.isnull().sum().
# 4.Cleaned Column Names: Column names were stripped of whitespace and converted to lowercase for easier access and consistency.
# 5.Handled Invalid Zero Values:
# 6.Imputed Missing Values:
# 7.Separated Features and Target:
# 8.Split Data into Training and Testing Sets:
# 9.Scaled Features: We applied StandardScaler to scale the numerical features.
# 10.Trained a Logistic Regression Model:
# 11.Evaluated Model Performance:

In [ ]:
# linear regression propability predition
y_prob = log_reg.predict_proba(x_test_scaled)

In [ ]:
y_prob[:20]

array([[0.39656534, 0.60343466],
       [0.88144694, 0.11855306],
       [0.70059423, 0.29940577],
       [0.75133964, 0.24866036],
       [0.96597848, 0.03402152],
       [0.83353637, 0.16646363],
       [0.51325247, 0.48674753],
       [0.07980775, 0.92019225],
       [0.91881166, 0.08118834],
       [0.15846649, 0.84153351],
       [0.72324833, 0.27675167],
       [0.52676562, 0.47323438],
       [0.86932801, 0.13067199],
       [0.88620334, 0.11379666],
       [0.71553212, 0.28446788],
       [0.65051916, 0.34948084],
       [0.28064511, 0.71935489],
       [0.91521738, 0.08478262],
       [0.19054078, 0.80945922],
       [0.89115616, 0.10884384]])

In [ ]:
y_prob_diabetic = y_prob[:,1]
y_prob_diabetic[:10]

array([0.60971073, 0.11835576, 0.29346313, 0.2508367 , 0.03320667,
       0.16852385, 0.4881643 , 0.92367511, 0.08143405, 0.8385896 ])

In [ ]:
#confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,y_pred)
cm

# [TN FP]
# [FN TP]

#  TN=true negative-actually non diabetic
#  FP=false positive-actually non diabetic but predicted diabetic
#  FN=false negative-actually diabetic but predicted non diabetic
#  TP=true positive-actually diabetic


array([[82, 18],
       [27, 27]])

In [ ]:
#classification repott
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

# here we will

              precision    recall  f1-score   support

           0       0.75      0.82      0.78       100
           1       0.60      0.50      0.55        54

    accuracy                           0.71       154
   macro avg       0.68      0.66      0.67       154
weighted avg       0.70      0.71      0.70       154



In [ ]:
# classification report
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

 #here we will see about precision,recall,f1-score,support
 # precision - how correct the model was when it said 0 or 1
 # recll: how many real 0 and 1 it found
 # f1: balance score of precision and recall
 # support : how ,many actual 0 and 1 patient

              precision    recall  f1-score   support

           0       0.75      0.82      0.78       100
           1       0.60      0.50      0.55        54

    accuracy                           0.71       154
   macro avg       0.68      0.66      0.67       154
weighted avg       0.70      0.71      0.70       154



In [ ]:
#next model we using here is SVM support vector
#machine it finds a strong margin based decision
#boundary that otean imporv well scalled datasets
#the  main reason to use is dateset is small in size,
#we did the scaling,chances are high to get better recall

In [ ]:
from sklearn.svm import SVC
svm_model=SVC(kernel='linear',probability=True)
svm_model.fit(x_train_scaled,y_train)

SVC(kernel='linear', probability=True)

In [ ]:
y_pred_svm=svm_model.predict(x_test_scaled)

#evaluating
svm_model.score(x_test_scaled,y_test)

0.7077922077922078

In [ ]:
y_prob_svm=svm_model.predict_proba(x_test_scaled)[:,1]


In [ ]:
y_prob_svm[:10]

array([[0.38265124, 0.61734876],
       [0.87007211, 0.12992789],
       [0.67973215, 0.32026785],
       [0.73763922, 0.26236078],
       [0.95966328, 0.04033672],
       [0.81606823, 0.18393177],
       [0.53339939, 0.46660061],
       [0.07900443, 0.92099557],
       [0.90177337, 0.09822663],
       [0.17729782, 0.82270218]])

In [ ]:
recap=pd.DataFrame({
    'y_test':y_test,
    'y_pred':y_pred
})
recap.head()

y_test  y_pred
44        0       1
672       0       0
700       0       0
630       1       0
81        0       0

In [ ]:
y_train_pred=svm_model.predict(x_train_scaled)
y_test_pred=svm_model.predict(x_test_scaled)



In [ ]:
#confusion matrics

from sklearn.metrics import confusion_matrix,classification_report
cm_svm = confusion_matrix(y_test,y_pred_svm)
cm_svm


array([[82, 18],
       [27, 27]])

In [ ]:
#classification report
print(classification_report(y_test,y_pred_svm))

              precision    recall  f1-score   support

           0       0.75      0.82      0.78       100
           1       0.60      0.50      0.55        54

    accuracy                           0.71       154
   macro avg       0.68      0.66      0.67       154
weighted avg       0.70      0.71      0.70       154



In [ ]:
y_prob_svm[:10]

array([[0.38265124, 0.61734876],
       [0.87007211, 0.12992789],
       [0.67973215, 0.32026785],
       [0.73763922, 0.26236078],
       [0.95966328, 0.04033672],
       [0.81606823, 0.18393177],
       [0.53339939, 0.46660061],
       [0.07900443, 0.92099557],
       [0.90177337, 0.09822663],
       [0.17729782, 0.82270218]])

In [ ]:
#RDC AUC Receiver Operating Characteristic Area Under the Curve

from sklearn.metrics import roc_auc_score
roc_auc_lr = roc_auc_score(y_test,y_prob[:,1])
roc_auc_svm = roc_auc_score(y_test,y_prob_svm)

roc_auc_lr,roc_auc_svm

# 81 for both lr and svm
# roc implies that both lr and svm correctly ranks a diabetic higher than a non diabetic 82% of the time
# slides the threshold from 0-1,computes recall and false positive at each step,plots the curve


(np.float64(0.8116666666666666), np.float64(0.8137037037037037))